services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/live/kekburger.students.nomorepartiesco.ru/fullchain.pem:/etc/nginx/certs/fullchain.pem
      - /etc/letsencrypt/live/kekburger.students.nomorepartiesco.ru/privkey.pem:/etc/nginx/certs/privkey.pem
    ports:
      - "443:443"
      - "80:80"
